# Generated by Django 4.1.3 on 2022-11-13 17:26

from django.db import migrations, models
import django.db.models.deletion
import groupridesapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('web_url', models.CharField(max_length=255, verbose_name='Website')),
                ('logo_url', models.CharField(max_length=255, verbose_name='Logo URL')),
                ('zip_code', models.CharField(max_length=5, validators=[groupridesapp.models.numeric_chars, groupridesapp.models.length_of_five], verbose_name='Zip Code')),
                ('private', models.BooleanField(verbose_name='Private')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Date Created')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Date Joined')),
                ('membership_expires', models.DateField(verbose_name='Membership Expires')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('membership_type', models.CharField(choices=[('1', 'Creator'), ('2', 'Admin'), ('3', 'Member'), ('4', 'Non-Member')], max_length=255, verbose_name='Membership Type')),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('email_address', models.EmailField(max_length=100, verbose_name='Email')),
                ('address', models.CharField(max_length=40, verbose_name='Address')),
                ('zip_code', models.CharField(max_length=5, validators=[groupridesapp.models.numeric_chars, groupridesapp.models.length_of_five], verbose_name='Zip Code')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Date Created')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Route Name')),
                ('route_url', models.CharField(max_length=255, verbose_name='Route URL')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Distance')),
                ('elevation', models.IntegerField(verbose_name='Elevation')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupridesapp.rider')),
            ],
        ),
    ]
