# Generated by Django 4.1.3 on 2022-11-21 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupridesapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='route_url',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_location_name',
        ),
    ]
