# Generated by Django 4.1.3 on 2022-11-13 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupridesapp', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Date Joined')),
                ('membership_expires', models.DateField(verbose_name='Membership Expires')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('membership_type', models.CharField(choices=[('1', 'Creator'), ('2', 'Admin'), ('3', 'Member'), ('4', 'Non-Member')], max_length=255, verbose_name='Membership Type')),
            ],
        ),
        migrations.RenameModel(
            old_name='Group',
            new_name='Club',
        ),
        migrations.DeleteModel(
            name='GroupMembership',
        ),
        migrations.AddField(
            model_name='clubmembership',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupridesapp.club'),
        ),
        migrations.AddField(
            model_name='clubmembership',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupridesapp.rider'),
        ),
    ]
