# Generated by Django 4.1.3 on 2022-11-23 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupridesapp', '0003_alter_eventoccurencemember_event_occurence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='privacy',
            field=models.IntegerField(choices=[(3, 'Current Members'), (4, 'Open')], verbose_name='Privacy'),
        ),
        migrations.AlterField(
            model_name='eventoccurence',
            name='privacy',
            field=models.IntegerField(choices=[(3, 'Current Members'), (4, 'Open')], verbose_name='Privacy'),
        ),
        migrations.AlterField(
            model_name='eventoccurencemember',
            name='event_occurence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupridesapp.eventoccurence'),
        ),
    ]
