# Generated by Django 4.1.3 on 2022-11-14 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupridesapp', '0004_alter_club_created_by_alter_clubmembership_rider_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubmembership',
            old_name='rider',
            new_name='user',
        ),
    ]
