# Generated by Django 4.1.3 on 2022-11-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupridesapp', '0006_eventoccurencemessage_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoccurencemessage',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
    ]
