# Generated by Django 4.1.3 on 2022-11-16 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupridesapp', '0006_event_alter_clubmembership_membership_type_userroute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventoccurencemember',
            name='event',
        ),
        migrations.AddField(
            model_name='eventoccurencemember',
            name='event_occurence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='groupridesapp.eventoccurence'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventoccurencemember',
            name='role',
            field=models.IntegerField(choices=[(1, 'Ride Leader'), (2, 'Rider')], default=2, verbose_name='Role'),
        ),
    ]
