# Generated by Django 4.1.3 on 2022-11-16 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupridesapp', '0007_remove_eventoccurencemember_event_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventoccurencemember',
            old_name='rider',
            new_name='user',
        ),
    ]
