# Generated by Django 4.1.3 on 2022-11-26 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groupridesapp', '0007_alter_eventoccurencemessage_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOccurenceMessageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_visit', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('event_occurence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupridesapp.eventoccurence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
