# Generated by Django 4.1.3 on 2022-11-16 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupridesapp', '0008_rename_rider_eventoccurencemember_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoccurence',
            name='privacy',
            field=models.IntegerField(choices=[(1, 'Creator'), (2, 'Admin'), (3, 'Member'), (4, 'Non-Member')], verbose_name='Privacy'),
        ),
        migrations.CreateModel(
            name='EventOccurenceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='Message')),
                ('event_occurence_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupridesapp.eventoccurencemember')),
            ],
        ),
    ]
