# Generated by Django 4.1.3 on 2022-11-26 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groupridesapp', '0008_eventoccurencemessagevisit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventoccurencemessage',
            name='event_occurence_member',
        ),
        migrations.AddField(
            model_name='eventoccurencemessage',
            name='event_occurence',
            field=models.ForeignKey(default=50, on_delete=django.db.models.deletion.CASCADE, to='groupridesapp.eventoccurence'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventoccurencemessage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
