# Generated by Django 4.1.3 on 2022-11-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupridesapp', '0009_alter_eventoccurence_privacy_eventoccurencemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_riders',
            field=models.IntegerField(default=16, verbose_name='Max Riders'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventoccurence',
            name='max_riders',
            field=models.IntegerField(default=16, verbose_name='Max Riders'),
            preserve_default=False,
        ),
    ]
