# Generated by Django 4.1.3 on 2022-11-26 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupridesapp', '0009_remove_eventoccurencemessage_event_occurence_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoccurencemessage',
            name='event_occurence_member',
            field=models.ForeignKey(default=41, on_delete=django.db.models.deletion.CASCADE, to='groupridesapp.eventoccurencemember'),
            preserve_default=False,
        ),
    ]
