# Generated by Django 4.1.3 on 2022-11-26 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupridesapp', '0010_eventoccurencemessage_event_occurence_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventoccurencemessage',
            name='event_occurence_member',
        ),
    ]
