# Generated by Django 4.1.3 on 2022-11-27 23:00

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('groupridesapp', '0011_remove_eventoccurencemessage_event_occurence_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoccurencemessage',
            name='message',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
