# Generated by Django 4.1.3 on 2022-11-18 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupridesapp', '0012_alter_eventoccurence_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoccurence',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groupridesapp.club'),
        ),
        migrations.AlterField(
            model_name='eventoccurence',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groupridesapp.event'),
        ),
    ]
