# Generated by Django 4.1.3 on 2022-11-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupridesapp', '0013_alter_eventoccurence_club_alter_eventoccurence_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='start_location_name',
            field=models.CharField(default='some start location name', max_length=240, verbose_name='Start Location'),
            preserve_default=False,
        ),
    ]
