# Generated by Django 4.1.3 on 2022-11-29 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupridesapp', '0014_alter_club_logo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='club',
            field=models.ForeignKey(blank=True, help_text='Only required if ride is private', on_delete=django.db.models.deletion.CASCADE, to='groupridesapp.club'),
        ),
        migrations.AlterField(
            model_name='eventoccurence',
            name='club',
            field=models.ForeignKey(blank=True, help_text='Only rquired if private is selected', null=True, on_delete=django.db.models.deletion.CASCADE, to='groupridesapp.club'),
        ),
    ]
