# Generated by Django 4.1.3 on 2022-11-29 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupridesapp', '0015_alter_event_club_alter_eventoccurence_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='club',
            field=models.ForeignKey(blank=True, help_text='Only required if ride is private', null=True, on_delete=django.db.models.deletion.CASCADE, to='groupridesapp.club'),
        ),
    ]
