# Generated by Django 4.1.3 on 2022-11-29 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupridesapp', '0016_alter_event_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groupridesapp.club'),
        ),
    ]
