# Generated by Django 4.1.3 on 2022-11-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupridesapp', '0017_route_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='shared',
            field=models.BooleanField(default=False, verbose_name='Share With Club'),
        ),
    ]
