# Generated by Django 4.1.3 on 2022-11-30 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupridesapp', '0018_route_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmembership',
            name='membership_type',
            field=models.IntegerField(choices=[(1, 'Creator'), (2, 'Admin'), (3, 'Ride Leader'), (4, 'Route Contributor'), (5, 'Member'), (6, 'Non-Member')], verbose_name='Membership Type'),
        ),
        migrations.AlterField(
            model_name='eventoccurence',
            name='privacy',
            field=models.IntegerField(choices=[(5, 'Current Members'), (6, 'Open')], verbose_name='Privacy'),
        ),
    ]
