# Generated by Django 4.1.3 on 2022-12-05 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupridesapp', '0019_alter_clubmembership_membership_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='privacy',
            field=models.IntegerField(choices=[(5, 'Current Members'), (6, 'Open')], verbose_name='Privacy'),
        ),
        migrations.AlterField(
            model_name='eventoccurence',
            name='club',
            field=models.ForeignKey(blank=True, help_text='Only required if private is selected', null=True, on_delete=django.db.models.deletion.CASCADE, to='groupridesapp.club'),
        ),
        migrations.AlterField(
            model_name='eventoccurencemember',
            name='event_occurence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groupridesapp.eventoccurence'),
        ),
    ]
