# Generated by Django 4.1.3 on 2022-12-08 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groupridesapp', '0024_clubmembership_one user membership per club'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubMembershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Request Date')),
                ('response_date', models.DateTimeField(null=True, verbose_name='Response Date')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Denied')], verbose_name='Request Status')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupridesapp.club')),
                ('responder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
