# Generated by Django 4.1.3 on 2022-12-16 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groupridesapp', '0026_alter_clubmembership_membership_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmembershiprequest',
            name='responder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clubmembershiprequest',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Response Date'),
        ),
        migrations.AlterField(
            model_name='clubmembershiprequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Denied')], default=1, verbose_name='Request Status'),
        ),
    ]
