# Generated by Django 4.1.3 on 2023-01-09 15:44

from django.db import migrations, models
import groupridesapp.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('groupridesapp', '0041_event_weekdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='description',
            field=tinymce.models.HTMLField(default='this is the description of the club that will display on the club card', max_length=3000, verbose_name='Club description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='frequency',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Daily'), (7, 'Weekly')], verbose_name='Recurrence'),
        ),
        migrations.AlterField(
            model_name='event',
            name='weekdays',
            field=groupridesapp.fields.ChoiceArrayField(base_field=models.IntegerField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], verbose_name='Weekdays'), blank=True, default=list, null=True, size=None),
        ),
    ]
