# Generated by Django 4.1.3 on 2023-01-09 16:24

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('groupridesapp', '0042_club_description_alter_event_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoccurencemessage',
            name='message',
            field=tinymce.models.HTMLField(verbose_name='Comment'),
        ),
    ]
