# Generated by Django 4.1.3 on 2023-01-11 01:52

from django.db import migrations, models
import groupridesapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('groupridesapp', '0044_alter_eventoccurencemessage_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.ImageField(default='default/bicycle.png', max_length=255, upload_to=groupridesapp.models.Club.image_upload_to),
        ),
    ]
