# Generated by Django 4.1.3 on 2022-11-13 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='First Name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Last Name',
        ),
    ]
